// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: customer/customer.proto

package customer

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEstimatePriceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimatePriceReq) Reset() {
	*x = GetEstimatePriceReq{}
	mi := &file_customer_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatePriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatePriceReq) ProtoMessage() {}

func (x *GetEstimatePriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatePriceReq.ProtoReflect.Descriptor instead.
func (*GetEstimatePriceReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *GetEstimatePriceReq) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetEstimatePriceReq) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type GetEstimatePriceRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance      int64                  `protobuf:"varint,6,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimatePriceRsp) Reset() {
	*x = GetEstimatePriceRsp{}
	mi := &file_customer_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatePriceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatePriceRsp) ProtoMessage() {}

func (x *GetEstimatePriceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatePriceRsp.ProtoReflect.Descriptor instead.
func (*GetEstimatePriceRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetEstimatePriceRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetEstimatePriceRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEstimatePriceRsp) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetEstimatePriceRsp) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetEstimatePriceRsp) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetEstimatePriceRsp) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GetEstimatePriceRsp) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_customer_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderReq) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateOrderReq) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateOrderReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Order         *OrderInfo             `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRsp) Reset() {
	*x = CreateOrderRsp{}
	mi := &file_customer_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRsp) ProtoMessage() {}

func (x *CreateOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRsp.ProtoReflect.Descriptor instead.
func (*CreateOrderRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOrderRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrderRsp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_customer_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Order         *OrderInfo             `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRsp) Reset() {
	*x = GetOrderRsp{}
	mi := &file_customer_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRsp) ProtoMessage() {}

func (x *GetOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRsp.ProtoReflect.Descriptor instead.
func (*GetOrderRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOrderRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrderRsp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListCustomerOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerOrdersReq) Reset() {
	*x = ListCustomerOrdersReq{}
	mi := &file_customer_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerOrdersReq) ProtoMessage() {}

func (x *ListCustomerOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerOrdersReq.ProtoReflect.Descriptor instead.
func (*ListCustomerOrdersReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{6}
}

func (x *ListCustomerOrdersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomerOrdersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCustomerOrdersRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Orders        []*OrderInfo           `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerOrdersRsp) Reset() {
	*x = ListCustomerOrdersRsp{}
	mi := &file_customer_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerOrdersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerOrdersRsp) ProtoMessage() {}

func (x *ListCustomerOrdersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerOrdersRsp.ProtoReflect.Descriptor instead.
func (*ListCustomerOrdersRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{7}
}

func (x *ListCustomerOrdersRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListCustomerOrdersRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListCustomerOrdersRsp) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListCustomerOrdersRsp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_customer_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{8}
}

func (x *CancelOrderReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Order         *OrderInfo             `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRsp) Reset() {
	*x = CancelOrderRsp{}
	mi := &file_customer_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRsp) ProtoMessage() {}

func (x *CancelOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRsp.ProtoReflect.Descriptor instead.
func (*CancelOrderRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelOrderRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrderRsp) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CustomerId    uint64                 `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DriverId      uint64                 `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance      int64                  `protobuf:"varint,7,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      int64                  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	EstimatePrice int64                  `protobuf:"varint,9,opt,name=estimate_price,json=estimatePrice,proto3" json:"estimate_price,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AcceptedAt    int64                  `protobuf:"varint,12,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,14,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	CancelledAt   int64                  `protobuf:"varint,15,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_customer_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{10}
}

func (x *OrderInfo) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *OrderInfo) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *OrderInfo) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *OrderInfo) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *OrderInfo) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *OrderInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *OrderInfo) GetEstimatePrice() int64 {
	if x != nil {
		return x.EstimatePrice
	}
	return 0
}

func (x *OrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrderInfo) GetAcceptedAt() int64 {
	if x != nil {
		return x.AcceptedAt
	}
	return 0
}

func (x *OrderInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *OrderInfo) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *OrderInfo) GetCancelledAt() int64 {
	if x != nil {
		return x.CancelledAt
	}
	return 0
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_customer_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{11}
}

type LogoutRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRsp) Reset() {
	*x = LogoutRsp{}
	mi := &file_customer_customer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRsp) ProtoMessage() {}

func (x *LogoutRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRsp.ProtoReflect.Descriptor instead.
func (*LogoutRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{12}
}

func (x *LogoutRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LogoutRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_customer_customer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{13}
}

func (x *LoginReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *LoginReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	TokenCreateAt int64                  `protobuf:"varint,4,opt,name=token_create_at,json=tokenCreateAt,proto3" json:"token_create_at,omitempty"`
	TokenTtl      int32                  `protobuf:"varint,5,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_customer_customer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{14}
}

func (x *LoginRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRsp) GetTokenCreateAt() int64 {
	if x != nil {
		return x.TokenCreateAt
	}
	return 0
}

func (x *LoginRsp) GetTokenTtl() int32 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

type GetVerifyCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeReq) Reset() {
	*x = GetVerifyCodeReq{}
	mi := &file_customer_customer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReq) ProtoMessage() {}

func (x *GetVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{15}
}

func (x *GetVerifyCodeReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

type GetVerifyCodeRsp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VerifyCode     string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	VerifyCodeTime int64                  `protobuf:"varint,4,opt,name=verify_code_time,json=verifyCodeTime,proto3" json:"verify_code_time,omitempty"`
	VerifyCodeTtl  int32                  `protobuf:"varint,5,opt,name=verify_code_ttl,json=verifyCodeTtl,proto3" json:"verify_code_ttl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVerifyCodeRsp) Reset() {
	*x = GetVerifyCodeRsp{}
	mi := &file_customer_customer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeRsp) ProtoMessage() {}

func (x *GetVerifyCodeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeRsp.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeRsp) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{16}
}

func (x *GetVerifyCodeRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVerifyCodeRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVerifyCodeRsp) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *GetVerifyCodeRsp) GetVerifyCodeTime() int64 {
	if x != nil {
		return x.VerifyCodeTime
	}
	return 0
}

func (x *GetVerifyCodeRsp) GetVerifyCodeTtl() int32 {
	if x != nil {
		return x.VerifyCodeTtl
	}
	return 0
}

var File_customer_customer_proto protoreflect.FileDescriptor

const file_customer_customer_proto_rawDesc = "" +
	"\n" +
	"\x17customer/customer.proto\x12\fapi.customer\x1a\x1cgoogle/api/annotations.proto\"O\n" +
	"\x13GetEstimatePriceReq\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"\xcb\x01\n" +
	"\x13GetEstimatePriceRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x03R\bdistance\x12\x1a\n" +
	"\bduration\x18\a \x01(\x03R\bduration\"b\n" +
	"\x0eCreateOrderReq\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"m\n" +
	"\x0eCreateOrderRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05order\x18\x03 \x01(\v2\x17.api.customer.OrderInfoR\x05order\"(\n" +
	"\vGetOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"j\n" +
	"\vGetOrderRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05order\x18\x03 \x01(\v2\x17.api.customer.OrderInfoR\x05order\"H\n" +
	"\x15ListCustomerOrdersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8c\x01\n" +
	"\x15ListCustomerOrdersRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06orders\x18\x03 \x03(\v2\x17.api.customer.OrderInfoR\x06orders\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"C\n" +
	"\x0eCancelOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"m\n" +
	"\x0eCancelOrderRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x05order\x18\x03 \x01(\v2\x17.api.customer.OrderInfoR\x05order\"\xd3\x03\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\x04R\n" +
	"customerId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x04R\bdriverId\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x06 \x01(\tR\vdestination\x12\x1a\n" +
	"\bdistance\x18\a \x01(\x03R\bdistance\x12\x1a\n" +
	"\bduration\x18\b \x01(\x03R\bduration\x12%\n" +
	"\x0eestimate_price\x18\t \x01(\x03R\restimatePrice\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vaccepted_at\x18\f \x01(\x03R\n" +
	"acceptedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\r \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x0e \x01(\x03R\n" +
	"finishedAt\x12!\n" +
	"\fcancelled_at\x18\x0f \x01(\x03R\vcancelledAt\"\v\n" +
	"\tLogoutReq\"9\n" +
	"\tLogoutRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\bLoginReq\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1f\n" +
	"\vverify_code\x18\x02 \x01(\tR\n" +
	"verifyCode\"\x93\x01\n" +
	"\bLoginRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_create_at\x18\x04 \x01(\x03R\rtokenCreateAt\x12\x1b\n" +
	"\ttoken_ttl\x18\x05 \x01(\x05R\btokenTtl\"0\n" +
	"\x10GetVerifyCodeReq\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\"\xb3\x01\n" +
	"\x10GetVerifyCodeRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\x12(\n" +
	"\x10verify_code_time\x18\x04 \x01(\x03R\x0everifyCodeTime\x12&\n" +
	"\x0fverify_code_ttl\x18\x05 \x01(\x05R\rverifyCodeTtl2\xf8\x06\n" +
	"\bCustomer\x12~\n" +
	"\rGetVerifyCode\x12\x1e.api.customer.GetVerifyCodeReq\x1a\x1e.api.customer.GetVerifyCodeRsp\"-\x82\xd3\xe4\x93\x02'\x12%/customer/get-verify-code/{telephone}\x12S\n" +
	"\x05Login\x12\x16.api.customer.LoginReq\x1a\x16.api.customer.LoginRsp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/customer/login\x12T\n" +
	"\x06Logout\x12\x17.api.customer.LogoutReq\x1a\x17.api.customer.LogoutRsp\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/customer/logout\x12~\n" +
	"\x10GetEstimatePrice\x12!.api.customer.GetEstimatePriceReq\x1a!.api.customer.GetEstimatePriceRsp\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/customer/get-estimate-price\x12f\n" +
	"\vCreateOrder\x12\x1c.api.customer.CreateOrderReq\x1a\x1c.api.customer.CreateOrderRsp\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/customer/orders\x12e\n" +
	"\bGetOrder\x12\x19.api.customer.GetOrderReq\x1a\x19.api.customer.GetOrderRsp\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/customer/orders/{order_id}\x12x\n" +
	"\x12ListCustomerOrders\x12#.api.customer.ListCustomerOrdersReq\x1a#.api.customer.ListCustomerOrdersRsp\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/customer/orders\x12x\n" +
	"\vCancelOrder\x12\x1c.api.customer.CancelOrderReq\x1a\x1c.api.customer.CancelOrderRsp\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/customer/orders/{order_id}/cancelB Z\x1ecustomer/api/customer;customerb\x06proto3"

var (
	file_customer_customer_proto_rawDescOnce sync.Once
	file_customer_customer_proto_rawDescData []byte
)

func file_customer_customer_proto_rawDescGZIP() []byte {
	file_customer_customer_proto_rawDescOnce.Do(func() {
		file_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_customer_proto_rawDesc), len(file_customer_customer_proto_rawDesc)))
	})
	return file_customer_customer_proto_rawDescData
}

var file_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_customer_customer_proto_goTypes = []any{
	(*GetEstimatePriceReq)(nil),   // 0: api.customer.GetEstimatePriceReq
	(*GetEstimatePriceRsp)(nil),   // 1: api.customer.GetEstimatePriceRsp
	(*CreateOrderReq)(nil),        // 2: api.customer.CreateOrderReq
	(*CreateOrderRsp)(nil),        // 3: api.customer.CreateOrderRsp
	(*GetOrderReq)(nil),           // 4: api.customer.GetOrderReq
	(*GetOrderRsp)(nil),           // 5: api.customer.GetOrderRsp
	(*ListCustomerOrdersReq)(nil), // 6: api.customer.ListCustomerOrdersReq
	(*ListCustomerOrdersRsp)(nil), // 7: api.customer.ListCustomerOrdersRsp
	(*CancelOrderReq)(nil),        // 8: api.customer.CancelOrderReq
	(*CancelOrderRsp)(nil),        // 9: api.customer.CancelOrderRsp
	(*OrderInfo)(nil),             // 10: api.customer.OrderInfo
	(*LogoutReq)(nil),             // 11: api.customer.LogoutReq
	(*LogoutRsp)(nil),             // 12: api.customer.LogoutRsp
	(*LoginReq)(nil),              // 13: api.customer.LoginReq
	(*LoginRsp)(nil),              // 14: api.customer.LoginRsp
	(*GetVerifyCodeReq)(nil),      // 15: api.customer.GetVerifyCodeReq
	(*GetVerifyCodeRsp)(nil),      // 16: api.customer.GetVerifyCodeRsp
}
var file_customer_customer_proto_depIdxs = []int32{
	10, // 0: api.customer.CreateOrderRsp.order:type_name -> api.customer.OrderInfo
	10, // 1: api.customer.GetOrderRsp.order:type_name -> api.customer.OrderInfo
	10, // 2: api.customer.ListCustomerOrdersRsp.orders:type_name -> api.customer.OrderInfo
	10, // 3: api.customer.CancelOrderRsp.order:type_name -> api.customer.OrderInfo
	15, // 4: api.customer.Customer.GetVerifyCode:input_type -> api.customer.GetVerifyCodeReq
	13, // 5: api.customer.Customer.Login:input_type -> api.customer.LoginReq
	11, // 6: api.customer.Customer.Logout:input_type -> api.customer.LogoutReq
	0,  // 7: api.customer.Customer.GetEstimatePrice:input_type -> api.customer.GetEstimatePriceReq
	2,  // 8: api.customer.Customer.CreateOrder:input_type -> api.customer.CreateOrderReq
	4,  // 9: api.customer.Customer.GetOrder:input_type -> api.customer.GetOrderReq
	6,  // 10: api.customer.Customer.ListCustomerOrders:input_type -> api.customer.ListCustomerOrdersReq
	8,  // 11: api.customer.Customer.CancelOrder:input_type -> api.customer.CancelOrderReq
	16, // 12: api.customer.Customer.GetVerifyCode:output_type -> api.customer.GetVerifyCodeRsp
	14, // 13: api.customer.Customer.Login:output_type -> api.customer.LoginRsp
	12, // 14: api.customer.Customer.Logout:output_type -> api.customer.LogoutRsp
	1,  // 15: api.customer.Customer.GetEstimatePrice:output_type -> api.customer.GetEstimatePriceRsp
	3,  // 16: api.customer.Customer.CreateOrder:output_type -> api.customer.CreateOrderRsp
	5,  // 17: api.customer.Customer.GetOrder:output_type -> api.customer.GetOrderRsp
	7,  // 18: api.customer.Customer.ListCustomerOrders:output_type -> api.customer.ListCustomerOrdersRsp
	9,  // 19: api.customer.Customer.CancelOrder:output_type -> api.customer.CancelOrderRsp
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_customer_customer_proto_init() }
func file_customer_customer_proto_init() {
	if File_customer_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_customer_proto_rawDesc), len(file_customer_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_customer_proto_goTypes,
		DependencyIndexes: file_customer_customer_proto_depIdxs,
		MessageInfos:      file_customer_customer_proto_msgTypes,
	}.Build()
	File_customer_customer_proto = out.File
	file_customer_customer_proto_goTypes = nil
	file_customer_customer_proto_depIdxs = nil
}
