// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"admin/internal/biz"
	"admin/internal/conf"
	"admin/internal/data"
	"admin/internal/registry"
	"admin/internal/server"
	"admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confService *conf.Service, confSecurity *conf.Security, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, confSecurity)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	adminRepo := data.NewAdminRepo(dataData)
	client, err := registry.NewConsulClient(confService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	consulRegistry, err := registry.NewConsulRegistry(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	driverBiz, cleanup2, err := biz.NewDriverBiz(consulRegistry, confService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	adminUsecase := biz.NewAdminUsecase(adminRepo, driverBiz, confSecurity)
	adminService := service.NewAdminService(adminUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, confSecurity, adminService, logger)
	app := newApp(logger, grpcServer, httpServer, consulRegistry)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
