// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: admin/admin.proto

package admin

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminAuditDriverProfile = "/api.admin.Admin/AuditDriverProfile"
const OperationAdminListPendingDrivers = "/api.admin.Admin/ListPendingDrivers"
const OperationAdminLogin = "/api.admin.Admin/Login"

type AdminHTTPServer interface {
	AuditDriverProfile(context.Context, *AuditDriverProfileRequest) (*AuditDriverProfileReply, error)
	ListPendingDrivers(context.Context, *ListPendingDriversRequest) (*ListPendingDriversReply, error)
	Login(context.Context, *AdminLoginRequest) (*AdminLoginReply, error)
}

func RegisterAdminHTTPServer(s *http.Server, srv AdminHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/login", _Admin_Login0_HTTP_Handler(srv))
	r.POST("/admin/driver/profile/audit", _Admin_AuditDriverProfile0_HTTP_Handler(srv))
	r.GET("/admin/driver/pending", _Admin_ListPendingDrivers0_HTTP_Handler(srv))
}

func _Admin_Login0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*AdminLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminLoginReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_AuditDriverProfile0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuditDriverProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminAuditDriverProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuditDriverProfile(ctx, req.(*AuditDriverProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuditDriverProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Admin_ListPendingDrivers0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPendingDriversRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminListPendingDrivers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPendingDrivers(ctx, req.(*ListPendingDriversRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPendingDriversReply)
		return ctx.Result(200, reply)
	}
}

type AdminHTTPClient interface {
	AuditDriverProfile(ctx context.Context, req *AuditDriverProfileRequest, opts ...http.CallOption) (rsp *AuditDriverProfileReply, err error)
	ListPendingDrivers(ctx context.Context, req *ListPendingDriversRequest, opts ...http.CallOption) (rsp *ListPendingDriversReply, err error)
	Login(ctx context.Context, req *AdminLoginRequest, opts ...http.CallOption) (rsp *AdminLoginReply, err error)
}

type AdminHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminHTTPClient(client *http.Client) AdminHTTPClient {
	return &AdminHTTPClientImpl{client}
}

func (c *AdminHTTPClientImpl) AuditDriverProfile(ctx context.Context, in *AuditDriverProfileRequest, opts ...http.CallOption) (*AuditDriverProfileReply, error) {
	var out AuditDriverProfileReply
	pattern := "/admin/driver/profile/audit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminAuditDriverProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) ListPendingDrivers(ctx context.Context, in *ListPendingDriversRequest, opts ...http.CallOption) (*ListPendingDriversReply, error) {
	var out ListPendingDriversReply
	pattern := "/admin/driver/pending"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminListPendingDrivers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminHTTPClientImpl) Login(ctx context.Context, in *AdminLoginRequest, opts ...http.CallOption) (*AdminLoginReply, error) {
	var out AdminLoginReply
	pattern := "/admin/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
