// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: admin/admin.proto

package admin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	TokenCreateAt int64                  `protobuf:"varint,4,opt,name=token_create_at,json=tokenCreateAt,proto3" json:"token_create_at,omitempty"`
	TokenTtl      int32                  `protobuf:"varint,5,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginReply) Reset() {
	*x = AdminLoginReply{}
	mi := &file_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReply) ProtoMessage() {}

func (x *AdminLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReply.ProtoReflect.Descriptor instead.
func (*AdminLoginReply) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminLoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginReply) GetTokenCreateAt() int64 {
	if x != nil {
		return x.TokenCreateAt
	}
	return 0
}

func (x *AdminLoginReply) GetTokenTtl() int32 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

func (x *AdminLoginReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AuditDriverProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      uint64                 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditDriverProfileRequest) Reset() {
	*x = AuditDriverProfileRequest{}
	mi := &file_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditDriverProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditDriverProfileRequest) ProtoMessage() {}

func (x *AuditDriverProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditDriverProfileRequest.ProtoReflect.Descriptor instead.
func (*AuditDriverProfileRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AuditDriverProfileRequest) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AuditDriverProfileRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *AuditDriverProfileRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AuditDriverProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditDriverProfileReply) Reset() {
	*x = AuditDriverProfileReply{}
	mi := &file_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditDriverProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditDriverProfileReply) ProtoMessage() {}

func (x *AuditDriverProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditDriverProfileReply.ProtoReflect.Descriptor instead.
func (*AuditDriverProfileReply) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AuditDriverProfileReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuditDriverProfileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuditDriverProfileReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListPendingDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingDriversRequest) Reset() {
	*x = ListPendingDriversRequest{}
	mi := &file_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingDriversRequest) ProtoMessage() {}

func (x *ListPendingDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingDriversRequest.ProtoReflect.Descriptor instead.
func (*ListPendingDriversRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListPendingDriversRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingDriversRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PendingDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      uint64                 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Telephone     string                 `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	IdNumber      string                 `protobuf:"bytes,5,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	IdImageA      string                 `protobuf:"bytes,6,opt,name=id_image_a,json=idImageA,proto3" json:"id_image_a,omitempty"`
	IdImageB      string                 `protobuf:"bytes,7,opt,name=id_image_b,json=idImageB,proto3" json:"id_image_b,omitempty"`
	LicenseImageA string                 `protobuf:"bytes,8,opt,name=license_image_a,json=licenseImageA,proto3" json:"license_image_a,omitempty"`
	LicenseImageB string                 `protobuf:"bytes,9,opt,name=license_image_b,json=licenseImageB,proto3" json:"license_image_b,omitempty"`
	DistinctCode  string                 `protobuf:"bytes,10,opt,name=distinct_code,json=distinctCode,proto3" json:"distinct_code,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingDriver) Reset() {
	*x = PendingDriver{}
	mi := &file_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingDriver) ProtoMessage() {}

func (x *PendingDriver) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingDriver.ProtoReflect.Descriptor instead.
func (*PendingDriver) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *PendingDriver) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *PendingDriver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PendingDriver) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *PendingDriver) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PendingDriver) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *PendingDriver) GetIdImageA() string {
	if x != nil {
		return x.IdImageA
	}
	return ""
}

func (x *PendingDriver) GetIdImageB() string {
	if x != nil {
		return x.IdImageB
	}
	return ""
}

func (x *PendingDriver) GetLicenseImageA() string {
	if x != nil {
		return x.LicenseImageA
	}
	return ""
}

func (x *PendingDriver) GetLicenseImageB() string {
	if x != nil {
		return x.LicenseImageB
	}
	return ""
}

func (x *PendingDriver) GetDistinctCode() string {
	if x != nil {
		return x.DistinctCode
	}
	return ""
}

func (x *PendingDriver) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListPendingDriversReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Drivers       []*PendingDriver       `protobuf:"bytes,4,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingDriversReply) Reset() {
	*x = ListPendingDriversReply{}
	mi := &file_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingDriversReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingDriversReply) ProtoMessage() {}

func (x *ListPendingDriversReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingDriversReply.ProtoReflect.Descriptor instead.
func (*ListPendingDriversReply) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListPendingDriversReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPendingDriversReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListPendingDriversReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPendingDriversReply) GetDrivers() []*PendingDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_admin_admin_proto protoreflect.FileDescriptor

const file_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x11admin/admin.proto\x12\tapi.admin\x1a\x1cgoogle/api/annotations.proto\"K\n" +
	"\x11AdminLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xae\x01\n" +
	"\x0fAdminLoginReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_create_at\x18\x04 \x01(\x03R\rtokenCreateAt\x12\x1b\n" +
	"\ttoken_ttl\x18\x05 \x01(\x05R\btokenTtl\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"l\n" +
	"\x19AuditDriverProfileRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x04R\bdriverId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"_\n" +
	"\x17AuditDriverProfileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"L\n" +
	"\x19ListPendingDriversRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xe3\x02\n" +
	"\rPendingDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x04R\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\ttelephone\x18\x03 \x01(\tR\ttelephone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tid_number\x18\x05 \x01(\tR\bidNumber\x12\x1c\n" +
	"\n" +
	"id_image_a\x18\x06 \x01(\tR\bidImageA\x12\x1c\n" +
	"\n" +
	"id_image_b\x18\a \x01(\tR\bidImageB\x12&\n" +
	"\x0flicense_image_a\x18\b \x01(\tR\rlicenseImageA\x12&\n" +
	"\x0flicense_image_b\x18\t \x01(\tR\rlicenseImageB\x12#\n" +
	"\rdistinct_code\x18\n" +
	" \x01(\tR\fdistinctCode\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\x91\x01\n" +
	"\x17ListPendingDriversReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x122\n" +
	"\adrivers\x18\x04 \x03(\v2\x18.api.admin.PendingDriverR\adrivers2\xeb\x02\n" +
	"\x05Admin\x12Z\n" +
	"\x05Login\x12\x1c.api.admin.AdminLoginRequest\x1a\x1a.api.admin.AdminLoginReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/admin/login\x12\x86\x01\n" +
	"\x12AuditDriverProfile\x12$.api.admin.AuditDriverProfileRequest\x1a\".api.admin.AuditDriverProfileReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/admin/driver/profile/audit\x12}\n" +
	"\x12ListPendingDrivers\x12$.api.admin.ListPendingDriversRequest\x1a\".api.admin.ListPendingDriversReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/admin/driver/pendingB\x17Z\x15admin/api/admin;adminb\x06proto3"

var (
	file_admin_admin_proto_rawDescOnce sync.Once
	file_admin_admin_proto_rawDescData []byte
)

func file_admin_admin_proto_rawDescGZIP() []byte {
	file_admin_admin_proto_rawDescOnce.Do(func() {
		file_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)))
	})
	return file_admin_admin_proto_rawDescData
}

var file_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_admin_admin_proto_goTypes = []any{
	(*AdminLoginRequest)(nil),         // 0: api.admin.AdminLoginRequest
	(*AdminLoginReply)(nil),           // 1: api.admin.AdminLoginReply
	(*AuditDriverProfileRequest)(nil), // 2: api.admin.AuditDriverProfileRequest
	(*AuditDriverProfileReply)(nil),   // 3: api.admin.AuditDriverProfileReply
	(*ListPendingDriversRequest)(nil), // 4: api.admin.ListPendingDriversRequest
	(*PendingDriver)(nil),             // 5: api.admin.PendingDriver
	(*ListPendingDriversReply)(nil),   // 6: api.admin.ListPendingDriversReply
}
var file_admin_admin_proto_depIdxs = []int32{
	5, // 0: api.admin.ListPendingDriversReply.drivers:type_name -> api.admin.PendingDriver
	0, // 1: api.admin.Admin.Login:input_type -> api.admin.AdminLoginRequest
	2, // 2: api.admin.Admin.AuditDriverProfile:input_type -> api.admin.AuditDriverProfileRequest
	4, // 3: api.admin.Admin.ListPendingDrivers:input_type -> api.admin.ListPendingDriversRequest
	1, // 4: api.admin.Admin.Login:output_type -> api.admin.AdminLoginReply
	3, // 5: api.admin.Admin.AuditDriverProfile:output_type -> api.admin.AuditDriverProfileReply
	6, // 6: api.admin.Admin.ListPendingDrivers:output_type -> api.admin.ListPendingDriversReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_admin_proto_init() }
func file_admin_admin_proto_init() {
	if File_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_proto_goTypes,
		DependencyIndexes: file_admin_admin_proto_depIdxs,
		MessageInfos:      file_admin_admin_proto_msgTypes,
	}.Build()
	File_admin_admin_proto = out.File
	file_admin_admin_proto_goTypes = nil
	file_admin_admin_proto_depIdxs = nil
}
