// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalAuditDriverProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      uint64                 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	AdminId       uint64                 `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalAuditDriverProfileRequest) Reset() {
	*x = InternalAuditDriverProfileRequest{}
	mi := &file_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalAuditDriverProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalAuditDriverProfileRequest) ProtoMessage() {}

func (x *InternalAuditDriverProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalAuditDriverProfileRequest.ProtoReflect.Descriptor instead.
func (*InternalAuditDriverProfileRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *InternalAuditDriverProfileRequest) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *InternalAuditDriverProfileRequest) GetAdminId() uint64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *InternalAuditDriverProfileRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *InternalAuditDriverProfileRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InternalAuditDriverProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalAuditDriverProfileReply) Reset() {
	*x = InternalAuditDriverProfileReply{}
	mi := &file_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalAuditDriverProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalAuditDriverProfileReply) ProtoMessage() {}

func (x *InternalAuditDriverProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalAuditDriverProfileReply.ProtoReflect.Descriptor instead.
func (*InternalAuditDriverProfileReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *InternalAuditDriverProfileReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InternalAuditDriverProfileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InternalAuditDriverProfileReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type InternalListPendingDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalListPendingDriversRequest) Reset() {
	*x = InternalListPendingDriversRequest{}
	mi := &file_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalListPendingDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalListPendingDriversRequest) ProtoMessage() {}

func (x *InternalListPendingDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalListPendingDriversRequest.ProtoReflect.Descriptor instead.
func (*InternalListPendingDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *InternalListPendingDriversRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *InternalListPendingDriversRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type InternalPendingDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      uint64                 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Telephone     string                 `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	IdNumber      string                 `protobuf:"bytes,5,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	IdImageA      string                 `protobuf:"bytes,6,opt,name=id_image_a,json=idImageA,proto3" json:"id_image_a,omitempty"`
	IdImageB      string                 `protobuf:"bytes,7,opt,name=id_image_b,json=idImageB,proto3" json:"id_image_b,omitempty"`
	LicenseImageA string                 `protobuf:"bytes,8,opt,name=license_image_a,json=licenseImageA,proto3" json:"license_image_a,omitempty"`
	LicenseImageB string                 `protobuf:"bytes,9,opt,name=license_image_b,json=licenseImageB,proto3" json:"license_image_b,omitempty"`
	DistinctCode  string                 `protobuf:"bytes,10,opt,name=distinct_code,json=distinctCode,proto3" json:"distinct_code,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalPendingDriver) Reset() {
	*x = InternalPendingDriver{}
	mi := &file_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalPendingDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPendingDriver) ProtoMessage() {}

func (x *InternalPendingDriver) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPendingDriver.ProtoReflect.Descriptor instead.
func (*InternalPendingDriver) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *InternalPendingDriver) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *InternalPendingDriver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InternalPendingDriver) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *InternalPendingDriver) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InternalPendingDriver) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *InternalPendingDriver) GetIdImageA() string {
	if x != nil {
		return x.IdImageA
	}
	return ""
}

func (x *InternalPendingDriver) GetIdImageB() string {
	if x != nil {
		return x.IdImageB
	}
	return ""
}

func (x *InternalPendingDriver) GetLicenseImageA() string {
	if x != nil {
		return x.LicenseImageA
	}
	return ""
}

func (x *InternalPendingDriver) GetLicenseImageB() string {
	if x != nil {
		return x.LicenseImageB
	}
	return ""
}

func (x *InternalPendingDriver) GetDistinctCode() string {
	if x != nil {
		return x.DistinctCode
	}
	return ""
}

func (x *InternalPendingDriver) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type InternalListPendingDriversReply struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int64                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int64                    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Drivers       []*InternalPendingDriver `protobuf:"bytes,4,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalListPendingDriversReply) Reset() {
	*x = InternalListPendingDriversReply{}
	mi := &file_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalListPendingDriversReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalListPendingDriversReply) ProtoMessage() {}

func (x *InternalListPendingDriversReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalListPendingDriversReply.ProtoReflect.Descriptor instead.
func (*InternalListPendingDriversReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *InternalListPendingDriversReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InternalListPendingDriversReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InternalListPendingDriversReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InternalListPendingDriversReply) GetDrivers() []*InternalPendingDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_driver_driver_proto protoreflect.FileDescriptor

const file_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x13driver/driver.proto\x12\n" +
	"api.driver\"\x8f\x01\n" +
	"!InternalAuditDriverProfileRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x04R\bdriverId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x04R\aadminId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"g\n" +
	"\x1fInternalAuditDriverProfileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"T\n" +
	"!InternalListPendingDriversRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xeb\x02\n" +
	"\x15InternalPendingDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x04R\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\ttelephone\x18\x03 \x01(\tR\ttelephone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tid_number\x18\x05 \x01(\tR\bidNumber\x12\x1c\n" +
	"\n" +
	"id_image_a\x18\x06 \x01(\tR\bidImageA\x12\x1c\n" +
	"\n" +
	"id_image_b\x18\a \x01(\tR\bidImageB\x12&\n" +
	"\x0flicense_image_a\x18\b \x01(\tR\rlicenseImageA\x12&\n" +
	"\x0flicense_image_b\x18\t \x01(\tR\rlicenseImageB\x12#\n" +
	"\rdistinct_code\x18\n" +
	" \x01(\tR\fdistinctCode\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xa2\x01\n" +
	"\x1fInternalListPendingDriversReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12;\n" +
	"\adrivers\x18\x04 \x03(\v2!.api.driver.InternalPendingDriverR\adrivers2\xfc\x01\n" +
	"\x06Driver\x12x\n" +
	"\x1aInternalAuditDriverProfile\x12-.api.driver.InternalAuditDriverProfileRequest\x1a+.api.driver.InternalAuditDriverProfileReply\x12x\n" +
	"\x1aInternalListPendingDrivers\x12-.api.driver.InternalListPendingDriversRequest\x1a+.api.driver.InternalListPendingDriversReplyB\x19Z\x17admin/api/driver;driverb\x06proto3"

var (
	file_driver_driver_proto_rawDescOnce sync.Once
	file_driver_driver_proto_rawDescData []byte
)

func file_driver_driver_proto_rawDescGZIP() []byte {
	file_driver_driver_proto_rawDescOnce.Do(func() {
		file_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)))
	})
	return file_driver_driver_proto_rawDescData
}

var file_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_driver_driver_proto_goTypes = []any{
	(*InternalAuditDriverProfileRequest)(nil), // 0: api.driver.InternalAuditDriverProfileRequest
	(*InternalAuditDriverProfileReply)(nil),   // 1: api.driver.InternalAuditDriverProfileReply
	(*InternalListPendingDriversRequest)(nil), // 2: api.driver.InternalListPendingDriversRequest
	(*InternalPendingDriver)(nil),             // 3: api.driver.InternalPendingDriver
	(*InternalListPendingDriversReply)(nil),   // 4: api.driver.InternalListPendingDriversReply
}
var file_driver_driver_proto_depIdxs = []int32{
	3, // 0: api.driver.InternalListPendingDriversReply.drivers:type_name -> api.driver.InternalPendingDriver
	0, // 1: api.driver.Driver.InternalAuditDriverProfile:input_type -> api.driver.InternalAuditDriverProfileRequest
	2, // 2: api.driver.Driver.InternalListPendingDrivers:input_type -> api.driver.InternalListPendingDriversRequest
	1, // 3: api.driver.Driver.InternalAuditDriverProfile:output_type -> api.driver.InternalAuditDriverProfileReply
	4, // 4: api.driver.Driver.InternalListPendingDrivers:output_type -> api.driver.InternalListPendingDriversReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_driver_driver_proto_init() }
func file_driver_driver_proto_init() {
	if File_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_driver_proto_goTypes,
		DependencyIndexes: file_driver_driver_proto_depIdxs,
		MessageInfos:      file_driver_driver_proto_msgTypes,
	}.Build()
	File_driver_driver_proto = out.File
	file_driver_driver_proto_goTypes = nil
	file_driver_driver_proto_depIdxs = nil
}
