// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: driver/driver.proto

package driver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driver_InternalAuditDriverProfile_FullMethodName = "/api.driver.Driver/InternalAuditDriverProfile"
	Driver_InternalListPendingDrivers_FullMethodName = "/api.driver.Driver/InternalListPendingDrivers"
)

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverClient interface {
	InternalAuditDriverProfile(ctx context.Context, in *InternalAuditDriverProfileRequest, opts ...grpc.CallOption) (*InternalAuditDriverProfileReply, error)
	InternalListPendingDrivers(ctx context.Context, in *InternalListPendingDriversRequest, opts ...grpc.CallOption) (*InternalListPendingDriversReply, error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) InternalAuditDriverProfile(ctx context.Context, in *InternalAuditDriverProfileRequest, opts ...grpc.CallOption) (*InternalAuditDriverProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalAuditDriverProfileReply)
	err := c.cc.Invoke(ctx, Driver_InternalAuditDriverProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) InternalListPendingDrivers(ctx context.Context, in *InternalListPendingDriversRequest, opts ...grpc.CallOption) (*InternalListPendingDriversReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalListPendingDriversReply)
	err := c.cc.Invoke(ctx, Driver_InternalListPendingDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
// All implementations must embed UnimplementedDriverServer
// for forward compatibility.
type DriverServer interface {
	InternalAuditDriverProfile(context.Context, *InternalAuditDriverProfileRequest) (*InternalAuditDriverProfileReply, error)
	InternalListPendingDrivers(context.Context, *InternalListPendingDriversRequest) (*InternalListPendingDriversReply, error)
	mustEmbedUnimplementedDriverServer()
}

// UnimplementedDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServer struct{}

func (UnimplementedDriverServer) InternalAuditDriverProfile(context.Context, *InternalAuditDriverProfileRequest) (*InternalAuditDriverProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalAuditDriverProfile not implemented")
}
func (UnimplementedDriverServer) InternalListPendingDrivers(context.Context, *InternalListPendingDriversRequest) (*InternalListPendingDriversReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalListPendingDrivers not implemented")
}
func (UnimplementedDriverServer) mustEmbedUnimplementedDriverServer() {}
func (UnimplementedDriverServer) testEmbeddedByValue()                {}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	// If the following call panics, it indicates UnimplementedDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_InternalAuditDriverProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalAuditDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InternalAuditDriverProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_InternalAuditDriverProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InternalAuditDriverProfile(ctx, req.(*InternalAuditDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_InternalListPendingDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalListPendingDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InternalListPendingDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_InternalListPendingDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InternalListPendingDrivers(ctx, req.(*InternalListPendingDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.driver.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalAuditDriverProfile",
			Handler:    _Driver_InternalAuditDriverProfile_Handler,
		},
		{
			MethodName: "InternalListPendingDrivers",
			Handler:    _Driver_InternalListPendingDrivers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver/driver.proto",
}
