server:
  http:
    addr: 0.0.0.0:8100
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 10s
security:
  jwt_secret: "change-me-use-long-random-secret-in-production"
  jwt_ttl_seconds: 3600

data:
  database:
    driver: mysql
    source: root:Mysql@123456@tcp(127.0.0.1:3306)/laomadj_customer?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
service:
  consul:
    addr: localhost:8500
  trace:
    otlp_endpoint: 192.168.56.1:4317
