service:
  consul:
    addr: localhost:8500
  trace:
    otlp_endpoint: 192.168.56.1:4317

server:
  http:
    addr: 0.0.0.0:10300
    timeout: 10s
  grpc:
    addr: 0.0.0.0:11300
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:Mysql@123456@tcp(127.0.0.1:3306)/laomadj_valuation?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
