// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"verify-code/internal/biz"
	"verify-code/internal/conf"
	"verify-code/internal/data"
	"verify-code/internal/registry"
	"verify-code/internal/server"
	"verify-code/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confService *conf.Service, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	verifyCodeService := service.NewVerifyCodeService()
	grpcServer := server.NewGRPCServer(confServer, greeterService, verifyCodeService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	client, err := registry.NewConsulClient(confService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	consulRegistry, err := registry.NewConsulRegistry(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, consulRegistry)
	return app, func() {
		cleanup()
	}, nil
}
