// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"customer/internal/biz"
	"customer/internal/conf"
	"customer/internal/data"
	"customer/internal/registry"
	"customer/internal/server"
	"customer/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, security *conf.Security, confService *conf.Service, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	customerData := data.NewCustomerData(dataData)
	client, err := registry.NewConsulClient(confService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	consulRegistry, err := registry.NewConsulRegistry(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	customerBiz, cleanup2, err := biz.NewCustomerBiz(consulRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	customerService := service.NewCustomerService(customerData, security, customerBiz)
	httpServer := server.NewHTTPServer(confServer, security, customerService, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer, consulRegistry)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
