// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"driver/internal/biz"
	"driver/internal/conf"
	"driver/internal/data"
	"driver/internal/registry"
	"driver/internal/server"
	"driver/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confService *conf.Service, confSecurity *conf.Security, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	driverData := data.NewDriverData(dataData)
	client, err := registry.NewConsulClient(confService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	consulRegistry, err := registry.NewConsulRegistry(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	driverBiz, cleanup2, err := biz.NewDriverBiz(consulRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	driverService := service.NewDriverService(driverData, driverBiz, confSecurity)
	grpcServer := server.NewGRPCServer(confServer, confService, greeterService, driverService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, confSecurity, driverService, logger)
	app := newApp(logger, grpcServer, httpServer, consulRegistry)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
