// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: driver/driver.proto

package driver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driver_GetVerifyCode_FullMethodName              = "/api.driver.Driver/GetVerifyCode"
	Driver_Register_FullMethodName                   = "/api.driver.Driver/Register"
	Driver_Login_FullMethodName                      = "/api.driver.Driver/Login"
	Driver_UpdateDriverProfile_FullMethodName        = "/api.driver.Driver/UpdateDriverProfile"
	Driver_UpdateWorkStatus_FullMethodName           = "/api.driver.Driver/UpdateWorkStatus"
	Driver_AcceptOrder_FullMethodName                = "/api.driver.Driver/AcceptOrder"
	Driver_StartOrder_FullMethodName                 = "/api.driver.Driver/StartOrder"
	Driver_FinishOrder_FullMethodName                = "/api.driver.Driver/FinishOrder"
	Driver_CancelOrder_FullMethodName                = "/api.driver.Driver/CancelOrder"
	Driver_GetOrder_FullMethodName                   = "/api.driver.Driver/GetOrder"
	Driver_ListPendingOrders_FullMethodName          = "/api.driver.Driver/ListPendingOrders"
	Driver_ListDriverOrders_FullMethodName           = "/api.driver.Driver/ListDriverOrders"
	Driver_InternalAuditDriverProfile_FullMethodName = "/api.driver.Driver/InternalAuditDriverProfile"
	Driver_InternalListPendingDrivers_FullMethodName = "/api.driver.Driver/InternalListPendingDrivers"
)

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverClient interface {
	// GetVerifyCode returns a login/register verification code.
	GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeReply, error)
	// Register creates a driver account.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	// Login authenticates a driver.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// UpdateDriverProfile updates the current driver's profile.
	UpdateDriverProfile(ctx context.Context, in *UpdateDriverProfileRequest, opts ...grpc.CallOption) (*UpdateDriverProfileReply, error)
	// UpdateWorkStatus updates the current driver's work status.
	UpdateWorkStatus(ctx context.Context, in *UpdateWorkStatusRequest, opts ...grpc.CallOption) (*UpdateWorkStatusReply, error)
	// AcceptOrder lets the current driver accept a pending order.
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderReply, error)
	// StartOrder lets the current driver start an accepted order.
	StartOrder(ctx context.Context, in *StartOrderRequest, opts ...grpc.CallOption) (*StartOrderReply, error)
	// FinishOrder lets the current driver finish a started order.
	FinishOrder(ctx context.Context, in *FinishOrderRequest, opts ...grpc.CallOption) (*FinishOrderReply, error)
	// CancelOrder lets the current driver cancel an accepted order.
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderReply, error)
	// GetOrder returns one order visible to the current driver.
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderReply, error)
	// ListPendingOrders returns pending orders available for drivers.
	ListPendingOrders(ctx context.Context, in *ListPendingOrdersRequest, opts ...grpc.CallOption) (*ListPendingOrdersReply, error)
	// ListDriverOrders returns orders assigned to the current driver.
	ListDriverOrders(ctx context.Context, in *ListDriverOrdersRequest, opts ...grpc.CallOption) (*ListDriverOrdersReply, error)
	// InternalAuditDriverProfile lets admins audit driver profile submissions.
	InternalAuditDriverProfile(ctx context.Context, in *InternalAuditDriverProfileRequest, opts ...grpc.CallOption) (*InternalAuditDriverProfileReply, error)
	// InternalListPendingDrivers returns drivers waiting for profile review.
	InternalListPendingDrivers(ctx context.Context, in *InternalListPendingDriversRequest, opts ...grpc.CallOption) (*InternalListPendingDriversReply, error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerifyCodeReply)
	err := c.cc.Invoke(ctx, Driver_GetVerifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, Driver_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Driver_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) UpdateDriverProfile(ctx context.Context, in *UpdateDriverProfileRequest, opts ...grpc.CallOption) (*UpdateDriverProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverProfileReply)
	err := c.cc.Invoke(ctx, Driver_UpdateDriverProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) UpdateWorkStatus(ctx context.Context, in *UpdateWorkStatusRequest, opts ...grpc.CallOption) (*UpdateWorkStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkStatusReply)
	err := c.cc.Invoke(ctx, Driver_UpdateWorkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOrderReply)
	err := c.cc.Invoke(ctx, Driver_AcceptOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StartOrder(ctx context.Context, in *StartOrderRequest, opts ...grpc.CallOption) (*StartOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOrderReply)
	err := c.cc.Invoke(ctx, Driver_StartOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) FinishOrder(ctx context.Context, in *FinishOrderRequest, opts ...grpc.CallOption) (*FinishOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishOrderReply)
	err := c.cc.Invoke(ctx, Driver_FinishOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderReply)
	err := c.cc.Invoke(ctx, Driver_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderReply)
	err := c.cc.Invoke(ctx, Driver_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ListPendingOrders(ctx context.Context, in *ListPendingOrdersRequest, opts ...grpc.CallOption) (*ListPendingOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingOrdersReply)
	err := c.cc.Invoke(ctx, Driver_ListPendingOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ListDriverOrders(ctx context.Context, in *ListDriverOrdersRequest, opts ...grpc.CallOption) (*ListDriverOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriverOrdersReply)
	err := c.cc.Invoke(ctx, Driver_ListDriverOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) InternalAuditDriverProfile(ctx context.Context, in *InternalAuditDriverProfileRequest, opts ...grpc.CallOption) (*InternalAuditDriverProfileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalAuditDriverProfileReply)
	err := c.cc.Invoke(ctx, Driver_InternalAuditDriverProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) InternalListPendingDrivers(ctx context.Context, in *InternalListPendingDriversRequest, opts ...grpc.CallOption) (*InternalListPendingDriversReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalListPendingDriversReply)
	err := c.cc.Invoke(ctx, Driver_InternalListPendingDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
// All implementations must embed UnimplementedDriverServer
// for forward compatibility.
type DriverServer interface {
	// GetVerifyCode returns a login/register verification code.
	GetVerifyCode(context.Context, *GetVerifyCodeRequest) (*GetVerifyCodeReply, error)
	// Register creates a driver account.
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	// Login authenticates a driver.
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// UpdateDriverProfile updates the current driver's profile.
	UpdateDriverProfile(context.Context, *UpdateDriverProfileRequest) (*UpdateDriverProfileReply, error)
	// UpdateWorkStatus updates the current driver's work status.
	UpdateWorkStatus(context.Context, *UpdateWorkStatusRequest) (*UpdateWorkStatusReply, error)
	// AcceptOrder lets the current driver accept a pending order.
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderReply, error)
	// StartOrder lets the current driver start an accepted order.
	StartOrder(context.Context, *StartOrderRequest) (*StartOrderReply, error)
	// FinishOrder lets the current driver finish a started order.
	FinishOrder(context.Context, *FinishOrderRequest) (*FinishOrderReply, error)
	// CancelOrder lets the current driver cancel an accepted order.
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderReply, error)
	// GetOrder returns one order visible to the current driver.
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderReply, error)
	// ListPendingOrders returns pending orders available for drivers.
	ListPendingOrders(context.Context, *ListPendingOrdersRequest) (*ListPendingOrdersReply, error)
	// ListDriverOrders returns orders assigned to the current driver.
	ListDriverOrders(context.Context, *ListDriverOrdersRequest) (*ListDriverOrdersReply, error)
	// InternalAuditDriverProfile lets admins audit driver profile submissions.
	InternalAuditDriverProfile(context.Context, *InternalAuditDriverProfileRequest) (*InternalAuditDriverProfileReply, error)
	// InternalListPendingDrivers returns drivers waiting for profile review.
	InternalListPendingDrivers(context.Context, *InternalListPendingDriversRequest) (*InternalListPendingDriversReply, error)
	mustEmbedUnimplementedDriverServer()
}

// UnimplementedDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServer struct{}

func (UnimplementedDriverServer) GetVerifyCode(context.Context, *GetVerifyCodeRequest) (*GetVerifyCodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVerifyCode not implemented")
}
func (UnimplementedDriverServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDriverServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDriverServer) UpdateDriverProfile(context.Context, *UpdateDriverProfileRequest) (*UpdateDriverProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDriverProfile not implemented")
}
func (UnimplementedDriverServer) UpdateWorkStatus(context.Context, *UpdateWorkStatusRequest) (*UpdateWorkStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkStatus not implemented")
}
func (UnimplementedDriverServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOrder not implemented")
}
func (UnimplementedDriverServer) StartOrder(context.Context, *StartOrderRequest) (*StartOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOrder not implemented")
}
func (UnimplementedDriverServer) FinishOrder(context.Context, *FinishOrderRequest) (*FinishOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishOrder not implemented")
}
func (UnimplementedDriverServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedDriverServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedDriverServer) ListPendingOrders(context.Context, *ListPendingOrdersRequest) (*ListPendingOrdersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingOrders not implemented")
}
func (UnimplementedDriverServer) ListDriverOrders(context.Context, *ListDriverOrdersRequest) (*ListDriverOrdersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriverOrders not implemented")
}
func (UnimplementedDriverServer) InternalAuditDriverProfile(context.Context, *InternalAuditDriverProfileRequest) (*InternalAuditDriverProfileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalAuditDriverProfile not implemented")
}
func (UnimplementedDriverServer) InternalListPendingDrivers(context.Context, *InternalListPendingDriversRequest) (*InternalListPendingDriversReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalListPendingDrivers not implemented")
}
func (UnimplementedDriverServer) mustEmbedUnimplementedDriverServer() {}
func (UnimplementedDriverServer) testEmbeddedByValue()                {}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	// If the following call panics, it indicates UnimplementedDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_GetVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).GetVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_GetVerifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).GetVerifyCode(ctx, req.(*GetVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_UpdateDriverProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).UpdateDriverProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_UpdateDriverProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).UpdateDriverProfile(ctx, req.(*UpdateDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_UpdateWorkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).UpdateWorkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_UpdateWorkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).UpdateWorkStatus(ctx, req.(*UpdateWorkStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_AcceptOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).AcceptOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_AcceptOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).AcceptOrder(ctx, req.(*AcceptOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StartOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StartOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_StartOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StartOrder(ctx, req.(*StartOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_FinishOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).FinishOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_FinishOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).FinishOrder(ctx, req.(*FinishOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ListPendingOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).ListPendingOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_ListPendingOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).ListPendingOrders(ctx, req.(*ListPendingOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ListDriverOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriverOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).ListDriverOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_ListDriverOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).ListDriverOrders(ctx, req.(*ListDriverOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_InternalAuditDriverProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalAuditDriverProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InternalAuditDriverProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_InternalAuditDriverProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InternalAuditDriverProfile(ctx, req.(*InternalAuditDriverProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_InternalListPendingDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalListPendingDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InternalListPendingDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_InternalListPendingDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InternalListPendingDrivers(ctx, req.(*InternalListPendingDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.driver.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerifyCode",
			Handler:    _Driver_GetVerifyCode_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Driver_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Driver_Login_Handler,
		},
		{
			MethodName: "UpdateDriverProfile",
			Handler:    _Driver_UpdateDriverProfile_Handler,
		},
		{
			MethodName: "UpdateWorkStatus",
			Handler:    _Driver_UpdateWorkStatus_Handler,
		},
		{
			MethodName: "AcceptOrder",
			Handler:    _Driver_AcceptOrder_Handler,
		},
		{
			MethodName: "StartOrder",
			Handler:    _Driver_StartOrder_Handler,
		},
		{
			MethodName: "FinishOrder",
			Handler:    _Driver_FinishOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Driver_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _Driver_GetOrder_Handler,
		},
		{
			MethodName: "ListPendingOrders",
			Handler:    _Driver_ListPendingOrders_Handler,
		},
		{
			MethodName: "ListDriverOrders",
			Handler:    _Driver_ListDriverOrders_Handler,
		},
		{
			MethodName: "InternalAuditDriverProfile",
			Handler:    _Driver_InternalAuditDriverProfile_Handler,
		},
		{
			MethodName: "InternalListPendingDrivers",
			Handler:    _Driver_InternalListPendingDrivers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver/driver.proto",
}
