// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: driver/driver.proto

package driver

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 修改司机状态的请求
type UpdateWorkStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // online/offline/busy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkStatusRequest) Reset() {
	*x = UpdateWorkStatusRequest{}
	mi := &file_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkStatusRequest) ProtoMessage() {}

func (x *UpdateWorkStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkStatusRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateWorkStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 修改司机状态的回复
type UpdateWorkStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkStatusReply) Reset() {
	*x = UpdateWorkStatusReply{}
	mi := &file_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkStatusReply) ProtoMessage() {}

func (x *UpdateWorkStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateWorkStatusReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateWorkStatusReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateWorkStatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateWorkStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 更新司机资料请求
type UpdateDriverProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdNumber      string                 `protobuf:"bytes,2,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	IdImageA      string                 `protobuf:"bytes,3,opt,name=id_image_a,json=idImageA,proto3" json:"id_image_a,omitempty"`
	IdImageB      string                 `protobuf:"bytes,4,opt,name=id_image_b,json=idImageB,proto3" json:"id_image_b,omitempty"`
	LicenseImageA string                 `protobuf:"bytes,5,opt,name=license_image_a,json=licenseImageA,proto3" json:"license_image_a,omitempty"`
	LicenseImageB string                 `protobuf:"bytes,6,opt,name=license_image_b,json=licenseImageB,proto3" json:"license_image_b,omitempty"`
	DistinctCode  string                 `protobuf:"bytes,7,opt,name=distinct_code,json=distinctCode,proto3" json:"distinct_code,omitempty"`
	TelephoneBak  string                 `protobuf:"bytes,8,opt,name=telephone_bak,json=telephoneBak,proto3" json:"telephone_bak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverProfileRequest) Reset() {
	*x = UpdateDriverProfileRequest{}
	mi := &file_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverProfileRequest) ProtoMessage() {}

func (x *UpdateDriverProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverProfileRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDriverProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetIdImageA() string {
	if x != nil {
		return x.IdImageA
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetIdImageB() string {
	if x != nil {
		return x.IdImageB
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetLicenseImageA() string {
	if x != nil {
		return x.LicenseImageA
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetLicenseImageB() string {
	if x != nil {
		return x.LicenseImageB
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetDistinctCode() string {
	if x != nil {
		return x.DistinctCode
	}
	return ""
}

func (x *UpdateDriverProfileRequest) GetTelephoneBak() string {
	if x != nil {
		return x.TelephoneBak
	}
	return ""
}

// 更新司机资料回复
type UpdateDriverProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverProfileReply) Reset() {
	*x = UpdateDriverProfileReply{}
	mi := &file_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverProfileReply) ProtoMessage() {}

func (x *UpdateDriverProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverProfileReply.ProtoReflect.Descriptor instead.
func (*UpdateDriverProfileReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverProfileReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateDriverProfileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *LoginRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

// 登录回复
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                                         // 登录成功后返回的token
	TokenCreateAt int64                  `protobuf:"varint,4,opt,name=token_create_at,json=tokenCreateAt,proto3" json:"token_create_at,omitempty"` // token生成时间
	TokenTtl      int32                  `protobuf:"varint,5,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`                  // token过期时间
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                       // 司机的状态
	DriverId      uint64                 `protobuf:"varint,7,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`                  // 司机ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_driver_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetTokenCreateAt() int64 {
	if x != nil {
		return x.TokenCreateAt
	}
	return 0
}

func (x *LoginReply) GetTokenTtl() int32 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

func (x *LoginReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginReply) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`                     // 手机号
	VerifyCode    string                 `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"` // 验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_driver_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *RegisterRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

// 注册回复
type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DriverId      uint64                 `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // 司机ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_driver_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterReply) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

// 获取验证码请求
type GetVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"` // 手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeRequest) Reset() {
	*x = GetVerifyCodeRequest{}
	mi := &file_driver_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeRequest) ProtoMessage() {}

func (x *GetVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{8}
}

func (x *GetVerifyCodeRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

// 获取验证码回复
type GetVerifyCodeReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                             // 状态码
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                        // 消息
	VerifyCode     string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`                // 验证码
	VerifyCodeTime int64                  `protobuf:"varint,4,opt,name=verify_code_time,json=verifyCodeTime,proto3" json:"verify_code_time,omitempty"` // 验证码生成时间
	VerifyCodeTtl  int32                  `protobuf:"varint,5,opt,name=verify_code_ttl,json=verifyCodeTtl,proto3" json:"verify_code_ttl,omitempty"`    // 验证码过期时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVerifyCodeReply) Reset() {
	*x = GetVerifyCodeReply{}
	mi := &file_driver_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReply) ProtoMessage() {}

func (x *GetVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{9}
}

func (x *GetVerifyCodeReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVerifyCodeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVerifyCodeReply) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *GetVerifyCodeReply) GetVerifyCodeTime() int64 {
	if x != nil {
		return x.VerifyCodeTime
	}
	return 0
}

func (x *GetVerifyCodeReply) GetVerifyCodeTtl() int32 {
	if x != nil {
		return x.VerifyCodeTtl
	}
	return 0
}

var File_driver_driver_proto protoreflect.FileDescriptor

const file_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x13driver/driver.proto\x12\n" +
	"api.driver\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x17UpdateWorkStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"]\n" +
	"\x15UpdateWorkStatusReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa3\x02\n" +
	"\x1aUpdateDriverProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tid_number\x18\x02 \x01(\tR\bidNumber\x12\x1c\n" +
	"\n" +
	"id_image_a\x18\x03 \x01(\tR\bidImageA\x12\x1c\n" +
	"\n" +
	"id_image_b\x18\x04 \x01(\tR\bidImageB\x12&\n" +
	"\x0flicense_image_a\x18\x05 \x01(\tR\rlicenseImageA\x12&\n" +
	"\x0flicense_image_b\x18\x06 \x01(\tR\rlicenseImageB\x12#\n" +
	"\rdistinct_code\x18\a \x01(\tR\fdistinctCode\x12#\n" +
	"\rtelephone_bak\x18\b \x01(\tR\ftelephoneBak\"H\n" +
	"\x18UpdateDriverProfileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\fLoginRequest\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1f\n" +
	"\vverify_code\x18\x02 \x01(\tR\n" +
	"verifyCode\"\xca\x01\n" +
	"\n" +
	"LoginReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_create_at\x18\x04 \x01(\x03R\rtokenCreateAt\x12\x1b\n" +
	"\ttoken_ttl\x18\x05 \x01(\x05R\btokenTtl\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\a \x01(\x04R\bdriverId\"P\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1f\n" +
	"\vverify_code\x18\x02 \x01(\tR\n" +
	"verifyCode\"r\n" +
	"\rRegisterReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\x04R\bdriverId\"4\n" +
	"\x14GetVerifyCodeRequest\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\"\xb5\x01\n" +
	"\x12GetVerifyCodeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\x12(\n" +
	"\x10verify_code_time\x18\x04 \x01(\x03R\x0everifyCodeTime\x12&\n" +
	"\x0fverify_code_ttl\x18\x05 \x01(\x05R\rverifyCodeTtl2\xb4\x04\n" +
	"\x06Driver\x12~\n" +
	"\rGetVerifyCode\x12 .api.driver.GetVerifyCodeRequest\x1a\x1e.api.driver.GetVerifyCodeReply\"+\x82\xd3\xe4\x93\x02%\x12#/driver/get-verify-code/{telephone}\x12^\n" +
	"\bRegister\x12\x1b.api.driver.RegisterRequest\x1a\x19.api.driver.RegisterReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0fdriver/register\x12R\n" +
	"\x05Login\x12\x18.api.driver.LoginRequest\x1a\x16.api.driver.LoginReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\fdriver/login\x12\x7f\n" +
	"\x13UpdateDriverProfile\x12&.api.driver.UpdateDriverProfileRequest\x1a$.api.driver.UpdateDriverProfileReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/driver/profile\x12u\n" +
	"\x10UpdateWorkStatus\x12#.api.driver.UpdateWorkStatusRequest\x1a!.api.driver.UpdateWorkStatusReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/driver/statusB\x1aZ\x18driver/api/driver;driverb\x06proto3"

var (
	file_driver_driver_proto_rawDescOnce sync.Once
	file_driver_driver_proto_rawDescData []byte
)

func file_driver_driver_proto_rawDescGZIP() []byte {
	file_driver_driver_proto_rawDescOnce.Do(func() {
		file_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)))
	})
	return file_driver_driver_proto_rawDescData
}

var file_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_driver_driver_proto_goTypes = []any{
	(*UpdateWorkStatusRequest)(nil),    // 0: api.driver.UpdateWorkStatusRequest
	(*UpdateWorkStatusReply)(nil),      // 1: api.driver.UpdateWorkStatusReply
	(*UpdateDriverProfileRequest)(nil), // 2: api.driver.UpdateDriverProfileRequest
	(*UpdateDriverProfileReply)(nil),   // 3: api.driver.UpdateDriverProfileReply
	(*LoginRequest)(nil),               // 4: api.driver.LoginRequest
	(*LoginReply)(nil),                 // 5: api.driver.LoginReply
	(*RegisterRequest)(nil),            // 6: api.driver.RegisterRequest
	(*RegisterReply)(nil),              // 7: api.driver.RegisterReply
	(*GetVerifyCodeRequest)(nil),       // 8: api.driver.GetVerifyCodeRequest
	(*GetVerifyCodeReply)(nil),         // 9: api.driver.GetVerifyCodeReply
}
var file_driver_driver_proto_depIdxs = []int32{
	8, // 0: api.driver.Driver.GetVerifyCode:input_type -> api.driver.GetVerifyCodeRequest
	6, // 1: api.driver.Driver.Register:input_type -> api.driver.RegisterRequest
	4, // 2: api.driver.Driver.Login:input_type -> api.driver.LoginRequest
	2, // 3: api.driver.Driver.UpdateDriverProfile:input_type -> api.driver.UpdateDriverProfileRequest
	0, // 4: api.driver.Driver.UpdateWorkStatus:input_type -> api.driver.UpdateWorkStatusRequest
	9, // 5: api.driver.Driver.GetVerifyCode:output_type -> api.driver.GetVerifyCodeReply
	7, // 6: api.driver.Driver.Register:output_type -> api.driver.RegisterReply
	5, // 7: api.driver.Driver.Login:output_type -> api.driver.LoginReply
	3, // 8: api.driver.Driver.UpdateDriverProfile:output_type -> api.driver.UpdateDriverProfileReply
	1, // 9: api.driver.Driver.UpdateWorkStatus:output_type -> api.driver.UpdateWorkStatusReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_driver_driver_proto_init() }
func file_driver_driver_proto_init() {
	if File_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_driver_proto_goTypes,
		DependencyIndexes: file_driver_driver_proto_depIdxs,
		MessageInfos:      file_driver_driver_proto_msgTypes,
	}.Build()
	File_driver_driver_proto = out.File
	file_driver_driver_proto_goTypes = nil
	file_driver_driver_proto_depIdxs = nil
}
